### ISSUE TITLE
快速滑动必现

### ISSUE THREAD

**Issue by LinkGitcode** [xmagicj/LazyFragment#3]
java.lang.IllegalStateException: Fragment PlaceHolderFragment{5019f3f} not attached to Activity
 at android.support.v4.app.Fragment.getResources(Fragment.java:639)
                                                                                      at android.support.v4.app.Fragment.getString(Fragment.java:674)
                                                                                      at com.xmagicj.android.lazyfragment.PlaceHolderFragment$1.run(PlaceHolderFragment.java:62)
 at android.os.Handler.handleCallback(Handler.java:815)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                                      at android.os.Looper.loop(Looper.java:207)

**Comment by LinkGitcode** [comment]
if (!TextUtils.isEmpty(info.getShowNumber())&&isAdded())

**Comment by xmagicj** [comment]
哈 是的.
Demo写的太急 没有仔细去测.
提的很好.
谢谢 已修正
